# Generated by Django 5.2.7 on 2026-05-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='firma_derecha_constancia',
            field=models.CharField(default='DRA. LIUBA ABIYOVA TÉLLEZ OSUNA', max_length=255, verbose_name='Firma derecha para constancias'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='firma_izquierda_constancia',
            field=models.CharField(default='Vo.Bo. Subdirección Académica', max_length=255, verbose_name='Firma izquierda para constancias'),
        ),
    ]
