# Generated by Django 5.2.7 on 2026-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_configuracionsistema_firma_derecha_constancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='costo_constancia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo de constancia'),
        ),
    ]
