# Generated by Django 5.2.7 on 2026-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_configuracionsistema_costo_constancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='firma_derecha_constancia',
            field=models.CharField(default='Dirección Académica Demo', max_length=255, verbose_name='Firma derecha para constancias'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='firma_izquierda_constancia',
            field=models.CharField(default='Control Escolar Demo', max_length=255, verbose_name='Firma izquierda para constancias'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='lema_anio',
            field=models.CharField(default='Sistema académico de demostración para portfolio profesional', max_length=255, verbose_name='Lema del año'),
        ),
    ]
