# Generated by Django 5.2.7 on 2026-06-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_configuracionsistema_firma_derecha_constancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='firma_derecha_constancia',
            field=models.CharField(default='DRA. LIUBA ABIYOVA TÉLLEZ OSUNA', max_length=255, verbose_name='Firma derecha para constancias'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='firma_izquierda_constancia',
            field=models.CharField(default='Vo.Bo. Subdirección Académica', max_length=255, verbose_name='Firma izquierda para constancias'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='lema_anio',
            field=models.CharField(default='2025, Año del Turismo Sostenible como Impulsor del Bienestar Social y Progreso', max_length=255, verbose_name='Lema del año'),
        ),
    ]
