# Generated by Django 5.2.7 on 2025-11-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_grupo'),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='tipo_calificacion',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('evidencia_final', 'Evidencia Final'), ('evaluacion_global', 'Evaluación Global')], default='unidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno', 'unidad', 'periodo', 'tipo_calificacion')},
        ),
    ]
