# Generated by Django 5.2.7 on 2026-03-08 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_alter_calificacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='parciales',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='materia',
            name='unidad_nueva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materia_temporal', to='evaluaciones.unidad'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='evaluaciones.carrera'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='materia',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='materias_legacy', to='evaluaciones.unidad'),
        ),
    ]
