# Generated by Django 5.2.7 on 2026-03-17 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_grupo'),
        ('evaluaciones', '0004_finalizar_unidad_materia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['alumno', 'unidad__numero', 'tipo_calificacion', 'numero_parcial'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='numero_parcial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_calificacion',
            field=models.CharField(choices=[('parcial', 'Parcial'), ('evidencia_final', 'Evidencia Final'), ('evaluacion_global', 'Evaluación Global')], default='parcial', max_length=20),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.unidad'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('alumno', 'unidad', 'periodo', 'tipo_calificacion', 'numero_parcial'), name='uq_calificacion_alumno_unidad_periodo_tipo_numero'),
        ),
    ]
