# Generated by Django 5.2.7 on 2026-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaevaluacion',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, upload_to='actas/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='docente_identificador',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='docente_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='total_horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='turno',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='actaevaluacion',
            name='promedio_grupo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
