# Generated by Django 5.2.7 on 2025-11-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='firma_derecha',
            field=models.CharField(default='DRA. LIUBA ABIYOVA TÉLLEZ OSUNA', max_length=100),
        ),
        migrations.AddField(
            model_name='constancia',
            name='firma_izquierda',
            field=models.CharField(default='Vo.Bo. Subdirección Académica', max_length=100),
        ),
    ]
