# Generated by Django 5.2.7 on 2025-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0002_constancia_firma_derecha_constancia_firma_izquierda'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='costo',
            field=models.FloatField(default=0.0, verbose_name='Costo de la constancia'),
        ),
    ]
