# Generated by Django 5.2.7 on 2025-11-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0003_constancia_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancia',
            name='lema_anio',
            field=models.CharField(default='2025, Año del Turismo Sostenible como Impulsor del Bienestar Social y Progreso', max_length=200, verbose_name='Lema del año'),
        ),
    ]
