# Generated by Django 5.2.7 on 2026-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0004_constancia_lema_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='firma_derecha',
            field=models.CharField(default='Dirección Académica Demo', max_length=100),
        ),
        migrations.AlterField(
            model_name='constancia',
            name='firma_izquierda',
            field=models.CharField(default='Control Escolar Demo', max_length=100),
        ),
        migrations.AlterField(
            model_name='constancia',
            name='lema_anio',
            field=models.CharField(default='Sistema académico de demostración para portfolio profesional', max_length=200, verbose_name='Lema del año'),
        ),
    ]
