# Generated by Django 5.2.7 on 2026-06-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constancias', '0005_alter_constancia_firma_derecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constancia',
            name='firma_derecha',
            field=models.CharField(default='DRA. LIUBA ABIYOVA TÉLLEZ OSUNA', max_length=100),
        ),
        migrations.AlterField(
            model_name='constancia',
            name='firma_izquierda',
            field=models.CharField(default='Vo.Bo. Subdirección Académica', max_length=100),
        ),
        migrations.AlterField(
            model_name='constancia',
            name='lema_anio',
            field=models.CharField(default='2025, Año del Turismo Sostenible como Impulsor del Bienestar Social y Progreso', max_length=200, verbose_name='Lema del año'),
        ),
    ]
