# Generated by Django 5.2.7 on 2025-11-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.CharField(default='101', help_text='Ejemplo: 101, 102, 201, etc.', max_length=10),
        ),
    ]
