# Generated by Django 5.2.7 on 2026-05-05 20:14

import alumnos.models
import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email_institucional',
            field=core.fields.EncryptedCharField(default='PENDIENTE', help_text="Debe terminar con @edubc.mx. Use 'PENDIENTE' si no tiene correo asignado.", max_length=500, validators=[alumnos.models.validate_email_domain, alumnos.models.validate_email_format]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro'), ('N/A', 'No especificado')], default='N/A', max_length=10),
        ),
    ]
