# Generated by Django 5.2.7 on 2026-06-11 12:35

import alumnos.models
import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_email_institucional_alter_alumno_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email_institucional',
            field=core.fields.EncryptedCharField(default='PENDIENTE', help_text="Debe terminar con @wasisv.com , Use 'PENDIENTE' si no tiene correo asignado.", max_length=500, validators=[alumnos.models.validate_email_domain, alumnos.models.validate_email_format]),
        ),
    ]
