"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from cryptography.fernet import Fernet, InvalidToken
from dotenv import load_dotenv
from django.conf.urls import handler403

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name, default=False):
    return os.getenv(str(name), str(default)).strip().lower() in ["1", "true", "yes", "on"]


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]

ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY')

# Validate encryption key
if not ENCRYPTION_KEY:
    print("❌ ADVERTENCIA: ENCRYPTION_KEY no encontrada en variables de entorno")
    print("❌ Generando clave temporal para desarrollo - NO USAR EN PRODUCCIÓN")
    ENCRYPTION_KEY = Fernet.generate_key().decode()
    print(f"🔑 Clave temporal: {ENCRYPTION_KEY}")
else:
    try:
        # Validate the key format
        Fernet(ENCRYPTION_KEY.encode())
        print("✅ Clave de cifrado válida")
    except (InvalidToken, ValueError) as e:
        print(f"❌ ERROR: Clave de cifrado inválida en ENCRYPTION_KEY")
        print(f"❌ Error: {e}")
        print("❌ Generando nueva clave temporal")
        ENCRYPTION_KEY = Fernet.generate_key().decode()
        print(f"🔑 Nueva clave temporal: {ENCRYPTION_KEY}")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-wasisv-demo-local-change-this"
)

DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
)

SITE_NAME = os.getenv("SITE_NAME", "WASISV")
SITE_SHORT_NAME = os.getenv("SITE_SHORT_NAME", "WASISV")
SITE_DESCRIPTION = os.getenv(
    "SITE_DESCRIPTION",
    "Sistema académico demo para portafolio profesional"
)
SITE_EMAIL_DOMAIN = os.getenv("SITE_EMAIL_DOMAIN", "wasisv.com")
SITE_CONTACT_EMAIL = os.getenv("SITE_CONTACT_EMAIL", "admin@wasisv.com")

DEMO_LOGIN_PASSWORD = os.getenv("DEMO_LOGIN_PASSWORD", "12345678")

DEMO_DELETE_PASSWORD_ALUMNOS = os.getenv("del_al_pass", "12345678")
DEMO_DELETE_PASSWORD_USUARIOS = os.getenv("del_us_pass", "12345678")
DEMO_DELETE_PASSWORD_CARRERAS = os.getenv("del_ca_pass", "12345678")

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    ""
)

X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'usuarios',        # Solo para el modelo de usuario
    'alumnos',
    'constancias',
    'evaluaciones',
    'administracion',
]

# Modelo de usuario personalizado
AUTH_USER_MODEL = 'usuarios.Usuario'

# URLs de autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'wasisv_uni_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '1234'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


AUTHENTICATION_BACKENDS = [
    'usuarios.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]



LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Tijuana'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'usuarios.Usuario'

# Login settings
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

# Email configuration (para autenticación por correo)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Para desarrollo

handler403 = 'core.views.forbidden_view'